import { createApp } from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router";
router.beforeEach((to, from, next) => {
  document.title = to.meta.title || "SalesHaven";
  next();
});
import store from "./store";
import "./assets/stylesheet/style.css";
import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import Cookies from "js-cookie";
import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { far } from "@fortawesome/free-regular-svg-icons";
library.add(fas, far);
import AOS from "aos";
import "aos/dist/aos.css";
const app = createApp(App);
app.component("font-awesome-icon", FontAwesomeIcon);
app.use(store);
app.use(router);
app.use(Cookies);
app.use(AOS.init());
store.dispatch("init");
app.mount("#app");
